"""Rule constant definitions."""

ACCOUNT_ATTRIBUTE_NAME = "Account No"
BALANCE_ATTRIBUTE_NAME = "BALANCE AMT"
CHECK_NO_ATTRIBUTE_NAME = "CHEQUE NO"
DATE_ATTRIBUTE_NAME = "VALUE DATE"
DEPOSIT_ATTRIBUTE_NAME = "DEPOSIT AMT"
RULE_ID_ATTRIBUTE_NAME = "RULE ID"
WITHDRAWAL_ATTRIBUTE_NAME = "WITHDRAWAL AMT"

TRANSACTION_TYPE_CHQ = "CHQ"
